# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stream_twitter', '0003_auto_20160904_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='slide',
            field=embed_video.fields.EmbedVideoField(default=datetime.datetime(2016, 9, 7, 17, 32, 15, 356662, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
