# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:40
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stream_twitter', '0004_tweet_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='slide',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
