# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_twitter', '0005_auto_20160908_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='myfile',
            field=models.URLField(blank=True),
        ),
    ]
