# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_twitter', '0006_tweet_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
